---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.appName }}-db-cm
  labels:
    app: {{ .Values.application.appName }}-db
  namespace: {{ .Values.application.namespace }}
data:
  MYSQL_USER: vikunja
  MYSQL_DATABASE: vikunja

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.appName }}-cm
  labels:
    app: {{ .Values.application.appName }}
  namespace: {{ .Values.application.namespace }}
data:
  VIKUNJA_SERVICE_PUBLICURL: "{{ .Values.application.protocol }}://{{ .Values.application.publicURL }}"
  VIKUNJA_DATABASE_HOST: {{ .Values.application.appName }}-db-svc
  VIKUNJA_DATABASE_TYPE: mysql