---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.appName }}-db-sec
  namespace: {{ .Values.application.namespace }}
data:
  MYSQL_ROOT_PASSWORD: a2QhbHNwIzkkRGEwJG1GZ2xRMVNsSGJt
  MYSQL_PASSWORD: a3MzRjkhd0I2JG0xJGZrUGw=
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.appName }}-sec
  namespace: {{ .Values.application.namespace }}
data:
  VIKUNJA_SERVICE_JWTSECRET: a3NqQWhkRmtldVNsYWpAMCRtQWw1MG1DMiRWbSFYJA==
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.appName }}-ingress-tls
  namespace: {{ .Values.application.namespace }}
type: kubernetes.io/tls
stringData:
  tls.key: ""
  tls.crt: ""