---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.appName }}-svc
  labels:
    app: {{ .Values.application.appName }}
  namespace: {{ .Values.application.namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.appName }}
  ports:
    - name: http
      port: 3456
      targetPort: 3456

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.appName }}-db-svc
  labels:
    app: {{ .Values.application.appName }}-db
  namespace: {{ .Values.application.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.appName }}-db
  ports:
    - port: 3306
      targetPort: 3306